[tasks.setup]
description = "Install Python dependencies"
run = 'python -m pip install -e ".[test]"'

[tasks.test]
description = "Test the Python project"
run = "python -m pytest"

[tasks.run]
description = "Run the Python project"
run = "python -m hello"
